### ISSUE TITLE
Host this on re-lmgtfy.com (can I contribute?)

### ISSUE THREAD

**Issue by gregschmit** [Arinerron/re-lmgtfy#5]
Hey, so I have this hosted on [re-lmgtfy.com](re-lmgtfy.com) (I noticed the domain was available).

I want to contribute to make this better. Is the owner active? I added an auto-copy-link feature but I want to know if you're accepting pull requests.

-gns

**Comment by eviltak** [comment]
The creator of this repository, unfortunately, has not been able to work on this for _quite_ a long time. You can still go ahead and open PRs though - I'll ask the owner to go through them when he's free (or possibly even give you write access to the repo).

The domain is a really great addition - where are you hosting the website?

**Comment by gregschmit** [comment]
I already added a simple javascript auto-copy-to-clipboard so I am gong to fork and put in a pull request.

I would definitely like write access. I find it weird that the master branch only has the README and LICENSE. We should probably consolidate to a master branch and a dev branch since this is a small project.

I am hosting it on a FreeBSD virtual machine using apache.

-gns

**Comment by gregschmit** [comment]
I created a pull request (#6) for that feature.

-gns

**Comment by Arinerron** [comment]
@schmitgreg Hey, thank you for contributing! Here's a list of changes I made just now:
- Merged #6 
- Given write access to @schmitgreg 
- Merged branch `gh-pages` into `master`
- Deleted branch `gh-pages`
- Created branch `dev`
- Set branch `master` to default

Does the server use CI or anything? Also, thanks for getting that domain, I appreciate it.

**Comment by eviltak** [comment]
I really think we should set up something like Travis CI (and maybe get a
dedicated server).

**Comment by gregschmit** [comment]
Awesome! Thanks @Arinerron, I appreciate you getting back to me.

I don't use CI (Travis or otherwise), but I have no problem setting it up that way it reflects the master branch. One thing we'd have to do is change the URL in the master branch, unless Travis allows you to write scripts (a simple find/replace would do) to modify the content prior to deploying it.

As for a dedicated server, yeah if someone wants to get one then that works. I use DigitalOcean and I don't want to spend $5/mo for this project unless I do something like put a PayPal donate button on the page to possibly get some funding.

For security, just so you guy know, the server is secured with SSH keys (ony mine as of now) and password authentication is disabled. I run PF (packet filter) to block off everything except ports I specifically use.

-gns
